version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
    - errcheck
    - errorlint
    - bodyclose
    - testifylint
    - paralleltest

  settings:
    errcheck:
      check-blank: false